### ISSUE TITLE
mô hình mvp

### ISSUE THREAD

**Issue by minh98** [liemvo/Flutter_bmi#1]
Chào bạn. mình thấy trong phần giới thiệu mô hình của bạn thì lớp presenter là lớp trung gian giữa dữ liệu và giao diện, lớp giao diện và lớp dữ liệu ko trực tiếp giao tiếp với nhau. nhưng mình thấy trong lớp view của bạn thì lại lấy dữ liệu trực tiếp từ lớp dữ liệu. bạn có thế giải thích cho mình hiểu rõ mô hình của bạn đang làm không ?. Cảm ơn bạn.

**Comment by liemvo** [comment]
Chào Minh, 
Model chứa các lớp dữ liệu để thay đổi giao diện của người dùng. Sau khi người dùng có thao tác thì lớp trung gian (presenter) sẽ yêu thay đổi giá trị của thuộc tính trong model. Sau khi thay đổi xong, presenter sẽ gọi view update lại. 

Model chỉ là đối tượng có dữ liệu sẽ được hiển thị trên giao diên. Mọi giao tiếp yêu cầu thay đổi model hay view đều do presenter thao tác

**Comment by liemvo** [comment]
Sau khi xem lại thì việc truyền model lên view không chuẩn xác lắm. Mình đã điều chỉnh lại để đúng hơn.
